// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1v9RA1SjVabCY58G0_Lisou-GxJy_BU',
    appId: '1:865097636802:web:fda49dd8bbe5873752945b',
    messagingSenderId: '865097636802',
    projectId: 'lushtemple-6e523',
    authDomain: 'lushtemple-6e523.firebaseapp.com',
    storageBucket: 'lushtemple-6e523.appspot.com',
    measurementId: 'G-TJ1FV8L0T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33OpDq5vnfFTGCULUHD14kwOlU7xcjQY',
    appId: '1:865097636802:android:c18ec4f65635ecf952945b',
    messagingSenderId: '865097636802',
    projectId: 'lushtemple-6e523',
    storageBucket: 'lushtemple-6e523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZIO5SCu5v4IEO0uPGtgAK0TDGutpis8',
    appId: '1:865097636802:ios:fd8b066a9c52ad8752945b',
    messagingSenderId: '865097636802',
    projectId: 'lushtemple-6e523',
    storageBucket: 'lushtemple-6e523.appspot.com',
    iosBundleId: 'com.example.lushTempleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZIO5SCu5v4IEO0uPGtgAK0TDGutpis8',
    appId: '1:865097636802:ios:fd8b066a9c52ad8752945b',
    messagingSenderId: '865097636802',
    projectId: 'lushtemple-6e523',
    storageBucket: 'lushtemple-6e523.appspot.com',
    iosBundleId: 'com.example.lushTempleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt1v9RA1SjVabCY58G0_Lisou-GxJy_BU',
    appId: '1:865097636802:web:b533cba089248efc52945b',
    messagingSenderId: '865097636802',
    projectId: 'lushtemple-6e523',
    authDomain: 'lushtemple-6e523.firebaseapp.com',
    storageBucket: 'lushtemple-6e523.appspot.com',
    measurementId: 'G-33J877KD1W',
  );
}
