// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClFVQQXdDqxDQv1hc3yxJoYA59AsN9xc',
    appId: '1:244602236458:web:2bf2bc55a0122434b0dd53',
    messagingSenderId: '244602236458',
    projectId: 'lushtempleapp',
    authDomain: 'lushtempleapp.firebaseapp.com',
    storageBucket: 'lushtempleapp.appspot.com',
    measurementId: 'G-G9V9L42QZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-UYiuWc7Vk6frdEtBLd-yoQoBUBHCK4',
    appId: '1:244602236458:android:fcea91fc8f418536b0dd53',
    messagingSenderId: '244602236458',
    projectId: 'lushtempleapp',
    storageBucket: 'lushtempleapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlNp6MEYaznUILxzDnb8TSdFQZ5zuAH0',
    appId: '1:244602236458:ios:0e2e3df9f22198bab0dd53',
    messagingSenderId: '244602236458',
    projectId: 'lushtempleapp',
    storageBucket: 'lushtempleapp.appspot.com',
    iosBundleId: 'com.example.lushTempleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlNp6MEYaznUILxzDnb8TSdFQZ5zuAH0',
    appId: '1:244602236458:ios:0e2e3df9f22198bab0dd53',
    messagingSenderId: '244602236458',
    projectId: 'lushtempleapp',
    storageBucket: 'lushtempleapp.appspot.com',
    iosBundleId: 'com.example.lushTempleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDClFVQQXdDqxDQv1hc3yxJoYA59AsN9xc',
    appId: '1:244602236458:web:805bb0c6eb4bc8ddb0dd53',
    messagingSenderId: '244602236458',
    projectId: 'lushtempleapp',
    authDomain: 'lushtempleapp.firebaseapp.com',
    storageBucket: 'lushtempleapp.appspot.com',
    measurementId: 'G-XFHBVKML59',
  );

}